spring.application.name=music
# Base de données MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/music_db
spring.datasource.username=safy
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# JWT
jwt.secret=MusicDistrib@Afrique2024#SecretKey!XYZ
jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tonemail@gmail.com
spring.mail.password=tonmotdepasseapp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL de base
app.base-url=http://localhost:8080